### PR TITLE
Simplify code generation for attestation protobufs

### PR DESCRIPTION
**Pull request by nick-mobilecoin**
The tonic and prost message build.rs files have been simplified.

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #11** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/protobufs/11" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/protobufs/11?utm_source=stack-comment).

**Review by jcape — APPROVED** [review]
This is a good start, but my suspicion is that the relative paths will cause problems on `crates.io`

**Comment by nick-mobilecoin** [comment]
> This is a good start, but my suspicion is that the relative paths will cause problems on `crates.io`

Yup it fails :(, added an item to #8

**Review by NotGyro — APPROVED** [review]
This looks good to me - greatly simplified.

**Pull request merged**
